// src/components/HelloWorld.vue
<template>
  <div>
    <p>{{ msg }}</p>
    <img :src="icon"
         alt="icon"
         style="width: 64px;">
    <i class="iconfont icon-spades" />
    <img src="/static/avatar.jpg"
         alt="icon"
         style="display: block;width: 128px;">
  </div>
</template>

<script>
import icon from '@/assets/images/icon.jpg';

export default {
  name: 'HelloWorld',
  data() {
    return {
      icon,
      msg: '',
    };
  },
  created() {
    this.getMsg();
  },
  methods: {
    getMsg() {
      setTimeout(() => {
        this.msg = 'Hello World!';
      }, 17);
    },
  },
};
</script>

<style lang="stylus" scoped>
p
  color: red
</style>

// react-app/src/components/HelloWorld.jsx
import React, { Component, Fragment } from 'react';
import './hello-word.styl';
import icon from '@/assets/images/icon.jpg';
import bg from '@/assets/images/bg.jpg';

let count = 1;

class HelloWorld extends Component {
  constructor(props) {
    super(props);
    this.state = {
      msg: '',
      msg2: '444',
    };
  }

  componentWillMount() {
    this.getMsg();
  }

  getMsg() {
    const a = setInterval(() => {
      this.setState({
        msg: count += 1,
      });
      if (count > 5) {
        clearInterval(a);
      }
    }, 1000);
  }

  render() {
    const { msg, msg2 } = this.state;
    return (
      <Fragment>
        <p>{msg}</p>
        <p>{msg2}</p>
        <img
          src={icon}
          alt="icon"
          style={{ width: '64px' }} />
        <i className="iconfont icon-spades" />
        <img
          src="/static/avatar.jpg"
          alt="icon"
          style={{ display: 'block', width: '128px' }} />
        <img src={bg} alt="bg" />
      </Fragment>
    );
  }
}

export default HelloWorld;
